version: '2'

services:
  app:
    build: .
    image: safercloud3000
    command: amber watch
    environment:
      DATABASE_URL: mysql://admin:password@db:3306/safercloud3000_development
    ports:
      - 3000:3000
    links:
      - db
    volumes:
    - .:/app
    - nodes:/app/node_modules
    - shards:/app/lib

  migrate:
    build: .
    image: safercloud3000
    command: bash -c 'while ! nc -q 1 db 3306 </dev/null; do sleep 1; done && amber db migrate seed'
    environment:
      DATABASE_URL: mysql://admin:password@db:3306/safercloud3000_development
    volumes:
      - .:/app
    links:
      - db

  db:
    image: mysql:5.6
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: safercloud3000_development
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    volumes:
    - db:/var/lib/mysql

volumes:
  db:
  nodes:
  shards:
